services:
  - postgresql
before_script:
  - psql -c 'create database coherence_test;' -U postgres
language: elixir
elixir:
  - 1.5
  - 1.4
otp_release:
  - 29.0
  - 19.3
sudo: false
notification:
  recipients:
    - smpallen99@yahoo.com
